name: Tests
on: [push]
jobs:
  test:
    strategy:
      matrix:
        luaVersion: ['5.1', '5.2', '5.3', '5.4', 'luau', 'luajit-2.1', 'luajit-openresty']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Lua and LuaRocks installation
      - uses: leafo/gh-actions-lua@v11
      - uses: leafo/gh-actions-luarocks@v4
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: install
        run: |
          luarocks install ./*.rockspec

      - name: tests
        run: |
          luarocks test
