name: Tests
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ['5.4']
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Lua and LuaRocks installation
      # https://github.com/LuaLS/luarocks-build-addon/blob/697f7a3bb9594265d0a3155d57daeded88b47b1e/.github/workflows/test.yml#L16-L24
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v6
        with:
          luaRocksVersion: "3.13.0"

      - name: install
        run: |
          luarocks install ./*.rockspec

      - name: tests
        run: |
          luarocks test
